# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wordslab-notebooks-lib',
                'doc_host': 'https://wordslab-org.github.io',
                'git_url': 'https://github.com/wordslab-org/wordslab-notebooks-lib',
                'lib_path': 'wordslab_notebooks_lib'},
  'syms': { 'wordslab_notebooks_lib.core': { 'wordslab_notebooks_lib.core.WordslabNotebooks': ( 'core.html#wordslabnotebooks',
                                                                                                'wordslab_notebooks_lib/core.py'),
                                             'wordslab_notebooks_lib.core.WordslabNotebooks.__init__': ( 'core.html#wordslabnotebooks.__init__',
                                                                                                         'wordslab_notebooks_lib/core.py')},
            'wordslab_notebooks_lib.notebook_context': { 'wordslab_notebooks_lib.notebook_context.get_notebook_data': ( 'notebook_context.html#get_notebook_data',
                                                                                                                        'wordslab_notebooks_lib/notebook_context.py')}}}
