# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wordslab-notebooks-lib',
                'doc_host': 'https://wordslab-org.github.io',
                'git_url': 'https://github.com/wordslab-org/wordslab-notebooks-lib',
                'lib_path': 'wordslab_notebooks_lib'},
  'syms': {'wordslab_notebooks_lib.core': {'wordslab_notebooks_lib.core.foo': ('core.html#foo', 'wordslab_notebooks_lib/core.py')}}}
