"""Python SDK to access wordslab-notebooks execution environment properties and services"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 3
try:
    from . import __version__
except:
    __version__ = "0.0.1"

# %% ../nbs/00_core.ipynb 4
from .env import WordslabNotebooksEnv
