# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_notebook_context.ipynb.

# %% auto 0
__all__ = ['NotebookContextManager', 'get_notebook_context', 'get_notebook_context_sync', 'format_for_llm']

# %% ../nbs/01_notebook_context.ipynb 2
import asyncio
from ipykernel.comm import Comm
from IPython import get_ipython

class NotebookContextManager:
    def __init__(self):
        self.comm_target = 'notebook_context_comm'
        self._comm = None
        self._registered = False
    
    def _ensure_registered(self):
        if not self._registered:
            self._comm = Comm(target_name=self.comm_target)
            self._registered = True
    
    async def get_notebook_context(self):
        self._ensure_registered()
        
        future = asyncio.Future()
        
        def handle_response(msg):
            if not future.done():
                future.set_result(msg['content']['data']['cells'])
        
        self._comm.on_msg(handle_response)
        self._comm.send({'action': 'request_cells'})
        
        try:
            result = await asyncio.wait_for(future, timeout=5.0)
            return result
        except asyncio.TimeoutError:
            raise TimeoutError("Failed to receive notebook context from frontend")
    
    def get_notebook_context_sync(self):
        try:
            import nest_asyncio
            nest_asyncio.apply()
        except ImportError:
            raise ImportError("nest_asyncio is required. Install with: pip install nest_asyncio")
        
        loop = asyncio.get_event_loop()
        return loop.run_until_complete(self.get_notebook_context())
    
    def format_context_for_llm(self, cells, include_outputs=True):
        context_parts = []
        
        for i, cell in enumerate(cells):
            if cell['type'] == 'markdown':
                context_parts.append(f"## Markdown Cell {i+1}")
                context_parts.append(cell['source'])
            elif cell['type'] == 'code':
                context_parts.append(f"## Code Cell {i+1}")
                context_parts.append(f"```python\n{cell['source']}\n```")
                
                if include_outputs and cell['outputs']:
                    context_parts.append("### Output:")
                    for output in cell['outputs']:
                        if output.get('text'):
                            context_parts.append(output['text'])
                        elif output.get('data'):
                            data = output['data']
                            if 'text/plain' in data:
                                context_parts.append(data['text/plain'])
            
            context_parts.append("")
        
        return "\n".join(context_parts)

_manager = NotebookContextManager()

async def get_notebook_context():
    return await _manager.get_notebook_context()

def get_notebook_context_sync():
    return _manager.get_notebook_context_sync()

def format_for_llm(include_outputs=True):
    cells = _manager.get_notebook_context_sync()
    return _manager.format_context_for_llm(cells, include_outputs)

