"""Predefined tools for LLMs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_tools.ipynb.

# %% ../nbs/03_tools.ipynb 2
from __future__ import annotations
from collections.abc import Iterator
import difflib
import fnmatch
from inspect import currentframe
import json
import os
from pathlib import Path
import re
import shutil
import time
from typing import List, Optional, Sequence, Any, NamedTuple, NotRequired, TypedDict

from tavily import TavilyClient

# %% auto 0
__all__ = ['ReadResult', 'WriteResult', 'GrepResult', 'SearchResult', 'ToolError', 'read_file_tool', 'write_file_tool',
           'grep_tool', 'search_replace_tool', 'read_file', 'write_file', 'grep', 'search_replace', 'tavily_search',
           'tavily_extract', 'tavily_crawl', 'tavily_map', 'tavily_research', 'tavily_search_tool',
           'tavily_extract_tool', 'tavily_crawl_tool', 'tavily_map_tool', 'tavily_research_tool']

# %% ../nbs/03_tools.ipynb 6
def _find_var(var: str):
    "Find the dict (globals or locals) containing var"
    frame = currentframe().f_back.f_back
    while frame:
        if var in frame.f_globals:
            return frame.f_globals[var]
        frame = frame.f_back
    return None

def _get_current_dir() -> Path:
    # Usage in Jupyterlab in wordslab notebooks
    nb_path = _find_var("__notebook_path")
    if nb_path is not None:
        return (Path(os.environ["WORDSLAB_WORKSPACE"]) / nb_path).parent
    return Path(os.environ.get("PWD", os.getcwd()))

def _is_valid_git_head(head_file: Path) -> bool:
    try:
        with open(head_file, encoding="utf-8") as f:
            content = f.read().strip()
        return content.startswith("ref:") or len(content) == 40 # COMMIT_HASH_LEN
    except (OSError, UnicodeDecodeError):
        return False


def _find_git_repo_root(start_path: Path | None = None) -> Path | None:
    current_dir = start_path.resolve() if start_path else _get_current_dir().resolve()

    while True:
        git_dir = current_dir / ".git"
        if git_dir.exists():
            head_file = git_dir / "HEAD" if git_dir.is_dir() else git_dir
            if head_file.exists() and _is_valid_git_head(head_file):
                return current_dir

        parent = current_dir.parent
        if parent == current_dir:
            return None

        current_dir = parent


def _get_project_root(start_path: Path | None = None) -> Path:
    git_root = _find_git_repo_root(start_path)
    if git_root is not None:
        return git_root

    return _get_current_dir().resolve()


def _resolve_path(path: str | Path, project_root: Path) -> Path:
    raw = Path(path).expanduser()
    if raw.is_absolute():
        return raw.resolve(strict=False)

    tried = _get_current_dir().resolve() / raw
    resolved = tried.resolve(strict=False)
    if resolved.exists():
        return resolved

    return (project_root.resolve() / raw).resolve(strict=False)


def _validate_in_project(resolved: Path, project_root: Path) -> str:
    try:
        resolved.relative_to(project_root.resolve())
    except ValueError:
        return (
            f"Cannot access file outside project directory: {resolved}. "
            f"Project root is {project_root.resolve()}"
        )
    return ""

# %% ../nbs/03_tools.ipynb 12
class ReadResult(TypedDict):
    path: str
    content: str
    offset: int
    lines_read: int
    was_truncated: bool
    error: NotRequired[str]


class WriteResult(TypedDict):
    path: str
    bytes_written: int
    file_existed: bool
    content: str
    error: NotRequired[str]


class GrepResult(TypedDict):
    matches: str
    match_count: int
    was_truncated: bool
    error: NotRequired[str]


class SearchResult(TypedDict):
    file: str
    blocks_applied: int
    lines_changed: int
    warnings: list[str]
    error: NotRequired[str]


class ToolError(Exception):
    pass


# ===========================================================================
# Tool versions — minimal parameters, prompt baked into docstring
# ===========================================================================


def read_file_tool(
    path: str, # Absolute or relative file path (resolved relative to the current notebook or to the project root).
    offset: int = 0, # 0-indexed line number to start reading from (default: 0).
    limit: int = 0 # Maximum number of lines to read; 0 means no explicit line limit (default: 0).
) -> ReadResult:
    """Use read_file to read the content of a file. It's designed to handle large files safely.

    **Arguments:**    
    - path: Absolute or relative file path (resolved relative to the current notebook or to the project root).
    - offset: 0-indexed line number to start reading from (default: 0).
    - limit: Maximum number of lines to read; 0 means no explicit line limit (default: 0).

    **IMPORTANT RULES:**
    
    - By default, it reads from the beginning of the file.
    - Use offset (line number) and limit (number of lines) to read specific parts or chunks of a file. This is efficient for exploring large files.
    - The result includes was_truncated: true if the file content was cut short due to size limits.
    - This is more efficient than using bash with cat or wc.

    **Strategy for large files:**

    1. Call read_file with a limit (e.g., 1000 lines) to get the start of the file.
    2. If was_truncated is true, the file is large. STOP and assess: do you already have enough information to answer the user's question? If yes, respond immediately — do not keep reading.
    3. If you need more, prefer targeted reads (e.g., jump to a specific offset, read the last 100 lines, search for a relevant section) over reading sequentially chunk by chunk.
    4. Do not call read_file more than 3 times on the same file without responding to the user first.

    **Do not read or explore:**
    - Model checkpoint directories or weight files (.bin, .safetensors, .pt, .gguf, optimizer states, etc.)
    - Binary files of any kind
    - Entire directory trees of training runs or large codebases. If the user provides paths to such files, treat them as references. Do not open them unless the user explicitly asks you to inspect a specific file.
    """
    try:
        if isinstance(path, str) and not path.strip():
            raise ValueError("Path cannot be empty")
        project_root = _get_project_root()
        resolved_path = _resolve_path(path, project_root)
        err = _validate_in_project(resolved_path, project_root)
        if err:
            raise ToolError(err)
        return {
            **read_file(
                str(resolved_path), offset=offset, limit=limit, max_bytes=64_000
            ),
        }
    except Exception as e:
        return {
            "path": str(path),
            "content": "",
            "offset": offset,
            "lines_read": 0,
            "error": f"{type(e).__name__}: {e}",
        }


def write_file_tool(
    path: str, # Absolute or relative file path (resolved relative to the current notebook or to the project root).
    content: str, # Text content to write.
    overwrite: bool = False # True to replace an existing file (default: False).
) -> WriteResult:
    """Use write_file to write content to a file.

    **Arguments:**
    - path: Absolute or relative file path (resolved relative to the current notebook or to the project root).
    - content: Text content to write.
    - overwrite: Must be set to true to overwrite an existing file (default: false)

    **IMPORTANT SAFETY RULES:**

    - By default, the tool will fail if the file already exists to prevent accidental data loss
    - To overwrite an existing file, you MUST set overwrite: true
    - To create a new file, just provide the path and content (overwrite defaults to false)
    - If parent directories don't exist, they will be created automatically

    **BEST PRACTICES:**

    - ALWAYS use the read_file tool first before overwriting an existing file to understand its current contents
    - ALWAYS prefer using search_replace to edit existing files rather than overwriting them completely
    - NEVER write new files unless explicitly required - prefer modifying existing files
    - NEVER proactively create documentation files (*.md) or README files unless explicitly requested
    - AVOID using emojis in file content unless the user explicitly requests them

    **Remember:** For editing existing files, prefer search_replace over write_file to preserve unchanged portions and avoid accidental data loss.
    """
    try:
        if isinstance(path, str) and not path.strip():
            raise ValueError("Path cannot be empty")
        project_root = _get_project_root()
        resolved_path = _resolve_path(path, project_root)
        err = _validate_in_project(resolved_path, project_root)
        if err:
            raise ToolError(err)
        return {
            **write_file(
                resolved_path,
                content,
                overwrite=overwrite,
                max_bytes=64_000,
                create_parent_dirs=True,
            ),
        }
    except Exception as e:
        return {
            "path": str(path),
            "bytes_written": 0,
            "content": "",
            "error": f"{type(e).__name__}: {e}",
        }


def grep_tool(
    pattern: str, # Regular-expression pattern compiled by the Python re module.
    path: str = "." # Root directory to search (resolved relative to the current notebook or to the project root).
) -> GrepResult:
    """Use grep to recursively search for a regular expression pattern in files.

    **Arguments:**
    - pattern: Regular-expression pattern compiled by the Python re module.
    - path: Root directory to search (resolved relative to the current notebook or to the project root).

     **IMPORTANT RULES:**

    - It's very fast and automatically ignores files that you should not read like .pyc files, .venv directories, etc.
    - Use this to find where functions are defined, how variables are used, or to locate specific error messages.
    """
    _src: str = ""  # for fallback result
    try:
        if path == ".":
            search_path = _get_current_dir()
        else:
            project_root = _get_project_root()
            resolved_path = _resolve_path(path, project_root)
            err = _validate_in_project(resolved_path, project_root)
            if err:
                raise ToolError(err)
            if not resolved_path.exists():
                raise FileNotFoundError(f"Path does not exist: {path}")
            search_path = resolved_path

        return {
            **grep(
                pattern,
                path=str(search_path),
                max_matches=100,
                max_output_bytes=64_000,
                exclude_patterns=None,
                case_sensitive=False,
                raise_on_exc=False,
            ),
        }
    except Exception as e:
        _src = str(path) if path != "." else str(_get_current_dir())
        return {
            "matches": "",
            "match_count": 0,
            "error": f"{type(e).__name__}: {e}",
        }


def search_replace_tool(
    file_path: str, # Absolute or relative path to the file to modify (resolved relative to the current notebook or to the project root)
    content: str # One or more SEARCH/REPLACE blocks defining the changes
) -> SearchResult:
    """Use search_replace to make targeted changes to files using SEARCH/REPLACE blocks. This tool finds exact text matches and replaces them.

    **Arguments:**
    - file_path: Absolute or relative path to the file to modify (resolved relative to the current notebook or to the project root).
    - content: One or more SEARCH/REPLACE blocks defining the changes

    The content format is:

        <<<<<<< SEARCH
        [exact text to find in the file]
        =======
        [exact text to replace it with]
        >>>>>>> REPLACE

    You can include multiple SEARCH/REPLACE blocks to make multiple changes to the same file.

    **IMPORTANT RULES:**

    - The SEARCH text must match EXACTLY (including whitespace, indentation, and line endings)
    - The SEARCH text must appear exactly once in the file - if it appears multiple times, the tool will error
    - Use at least 5 equals signs (=====) between SEARCH and REPLACE sections
    - The tool will provide detailed error messages showing context if search text is not found
    - Each search/replace block is applied in order, so later blocks see the results of earlier ones
    - Be careful with escape sequences in string literals - use \\n not \\n for newlines in code
    """
    try:
        project_root = _get_project_root()
        resolved_path = _resolve_path(file_path, project_root)
        err = _validate_in_project(resolved_path, project_root)
        if err:
            raise ToolError(err)
        return {
            **search_replace(
                resolved_path,
                content,
                max_content_size=100_000,
                fuzzy_threshold=0.9,
                create_backup=False,
            ),
        }
    except Exception as e:
        return {
            "file": str(file_path),
            "blocks_applied": 0,
            "lines_changed": 0,
            "error": f"{type(e).__name__}: {e}",
        }


# ===========================================================================
# Read file
# ===========================================================================

# Use read_file to read the content of a file. It is designed to handle large
# files safely.
#
# By default it reads from the beginning of the file. Use *offset* (0-indexed
# line number) and *limit* (max lines) to read specific parts. The return
# value includes *was_truncated* when the file was cut short.
#
# Strategy for large files:
# 1. Start with a reasonable *limit* (e.g. 1000) to get a head sample.
# 2. If truncated, decide whether you already have enough info.
# 3. Prefer targeted reads over sequential chunk-by-chunk reads.
# 4. Do not read more than 3 times on the same file without acting on what
#    you have learned.


def read_file(
    path: str | Path,
    *,
    offset: int = 0,
    limit: int = 0,
    max_bytes: int = 64_000,
) -> ReadResult:
    """Read a text file, returning content from a specific line range.

    Parameters
    ----------
    path
        Absolute or relative file path.
    offset
        0-indexed line number to start reading from. Defaults to 0.
    limit
        Maximum number of lines to read. ``None`` means no explicit
        line limit (only bounded by *max_bytes*).
    max_bytes
        Hard cap on bytes read in one call. Defaults to 64 000.

    Returns
    -------
    ReadResult
        Contains *path*, *content*, *offset*, *lines_read*, and
        *was_truncated*.

    Raises
    ------
    ValueError
        When *path* is empty, *offset* is negative, or *limit* is
        non-positive.
    FileNotFoundError
        When the path does not point to an existing file.
    IsADirectoryError
        When the path is a directory.
    """
    if isinstance(path, str) and not path.strip():
        raise ValueError("Path cannot be empty")
    if offset < 0:
        raise ValueError("Offset cannot be negative")
    if limit is not None and limit <= 0:
        raise ValueError("Limit, if provided, must be a positive number")

    file_path = Path(path).expanduser()
    if not file_path.is_absolute():
        file_path = Path.cwd() / file_path
    file_path = file_path.resolve()

    if not file_path.exists():
        raise FileNotFoundError(f"File not found at: {file_path}")
    if file_path.is_dir():
        raise IsADirectoryError(f"Path is a directory, not a file: {file_path}")

    lines: list[str] = []
    bytes_read = 0
    was_truncated = True

    with open(file_path, "rb") as f:
        line_index = 0
        while raw_line := f.readline():
            if line_index < offset:
                line_index += 1
                continue

            if limit > 0 and len(lines) >= limit:
                break

            line_bytes = len(raw_line)
            if bytes_read + line_bytes > max_bytes:
                break

            lines.append(raw_line.decode("utf-8", errors="replace"))
            bytes_read += line_bytes
            line_index += 1
        else:
            was_truncated = False

    return {
        "path": str(file_path),
        "content": "".join(lines),
        "offset": offset,
        "lines_read": len(lines),
        "was_truncated": was_truncated,
    }


# ===========================================================================
# Write file
# ===========================================================================

# Use write_file to create or overwrite a UTF-8 file.
#
# Safety:
# - Fails if the file already exists unless ``overwrite=True``.
# - Parent directories are created automatically.
#
# Best practices:
# - Always read a file before overwriting it.
# - Prefer ``search_replace`` for editing existing files.
# - Never write new files unless explicitly required.


def write_file(
    path: str | Path,
    content: str,
    *,
    overwrite: bool = False,
    max_bytes: int = 64_000,
    create_parent_dirs: bool = True,
) -> WriteResult:
    """Create or overwrite a UTF-8 text file.

    Parameters
    ----------
    path
        Absolute or relative file path.
    content
        Text to write.
    overwrite
        ``True`` to replace an existing file. Defaults to ``False``.
    max_bytes
        Hard cap for the encoded content size.
    create_parent_dirs
        Create missing parent directories automatically.

    Returns
    -------
    WriteResult
        Contains *path*, *bytes_written*, *file_existed*, and *content*.

    Raises
    ------
    ValueError
        When *path* is empty or content exceeds *max_bytes*.
    FileExistsError
        When the file exists and *overwrite* is ``False``.
    NotADirectoryError
        When a parent directory does not exist and *create_parent_dirs*
        is ``False``.
    """
    if isinstance(path, str) and not path.strip():
        raise ValueError("Path cannot be empty")

    content_bytes = len(content.encode("utf-8"))
    if content_bytes > max_bytes:
        raise ValueError(f"Content exceeds {max_bytes} bytes limit")

    file_path = Path(path).expanduser()
    if not file_path.is_absolute():
        file_path = Path.cwd() / file_path
    file_path = file_path.resolve()

    file_existed = file_path.exists()

    if file_existed and not overwrite:
        raise FileExistsError(
            f"File {file_path!r} exists. Set overwrite=True to replace."
        )

    if create_parent_dirs:
        file_path.parent.mkdir(parents=True, exist_ok=True)
    elif not file_path.parent.exists():
        raise NotADirectoryError(f"Parent directory does not exist: {file_path.parent}")

    file_path.write_text(content, encoding="utf-8")

    return {
        "path": str(file_path),
        "bytes_written": content_bytes,
        "file_existed": file_existed,
        "content": content,
    }


# ===========================================================================
# Grep
# ===========================================================================

# Use grep to recursively search for a regular expression pattern in files.
# It is fast and automatically ignores compiled artefacts and common
# build directories.

_DEFAULT_EXCLUDE: list[str] = [
    ".venv/",
    "venv/",
    "node_modules/",
    ".git/",
    "__pycache__/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".tox/",
    ".nox/",
    ".coverage/",
    "htmlcov/",
    "dist/",
    "build/",
    ".idea/",
    ".vscode/",
    "*.egg-info",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".DS_Store",
    "Thumbs.db",
    ".ipynb_checkpoints/"
]


def grep(
    pattern: str,
    path: str | Path = ".",
    *,
    max_matches: int = 100,
    max_output_bytes: int = 64_000,
    exclude_patterns: list[str] | None = None,
    case_sensitive: bool = False,
    raise_on_exc: bool = False,
) -> GrepResult:
    """Recursively search files for a regular-expression pattern.

    Parameters
    ----------
    pattern
        Regular-expression compiled by :mod:`re`.
    path
        Root directory to search. Defaults to the current working
        directory.
    max_matches
        Maximum number of match lines to return. The tool reports
        ``was_truncated=True`` when hitting this cap.
    max_output_bytes
        Hard cap on the combined length of returned match lines.
    exclude_patterns
        Glob-like patterns to skip.  Directories should end with ``/``.
        Falls back to a built-in set of common artefacts when ``None``.
    case_sensitive
        ``False`` enables case-insensitive matching.
    raise_on_exc
        ``True`` to propagate ``OSError`` from unreadable files
        instead of silently skipping them.

    Returns
    -------
    GrepResult
        Contains *matches*, *match_count*, and *was_truncated*.

    Raises
    ------
    ValueError
        When *pattern* is blank or contains invalid regex syntax.
    FileNotFoundError
        When *path* does not exist.
    """
    if not pattern.strip():
        raise ValueError("Empty search pattern provided.")

    root = Path(path).expanduser()
    if not root.is_absolute():
        root = Path.cwd() / root
    root = root.resolve()

    if not root.exists():
        raise FileNotFoundError(f"Path does not exist: {path}")

    excludes = exclude_patterns or _DEFAULT_EXCLUDE

    flags = 0 if case_sensitive else re.IGNORECASE
    try:
        compiled = re.compile(pattern, flags)
    except re.error as exc:
        raise ValueError(f"Invalid regex pattern: {exc}") from exc

    output_lines: list[str] = []
    bytes_used = 0
    truncated = False

    for fpath in _iter_files(root):
        if _should_exclude(fpath, excludes):
            continue

        if len(output_lines) >= max_matches:
            truncated = True
            break

        try:
            raw = fpath.read_bytes()
        except OSError:
            if raise_on_exc:
                raise
            continue

        if b"\x00" in raw[:8192]:
            continue

        text = raw.decode("utf-8", errors="ignore")

        for lineno, line in enumerate(text.splitlines(), start=1):
            if compiled.search(line):
                out = f"{fpath}:{lineno}:{line}"
                output_lines.append(out)
                bytes_used += len(out.encode("utf-8"))
                if bytes_used >= max_output_bytes:
                    truncated = True
                    break

        if truncated:
            break

    final_output = "\n".join(output_lines)
    final_bytes = len(final_output.encode("utf-8"))
    if final_bytes > max_output_bytes:
        truncated = True
        final_output = final_output[:max_output_bytes]

    return {
        "matches": final_output,
        "match_count": len(output_lines),
        "was_truncated": truncated,
    }


def _iter_files(root: Path) -> Iterator[Path]:
    try:
        for p in sorted(root.rglob("*"), key=lambda pth: str(pth)):
            if p.is_file():
                yield p
    except (PermissionError, OSError):
        return


def _should_exclude(fpath: Path, excludes: list[str]) -> bool:
    parts = fpath.parts
    for pat in excludes:
        if pat.endswith("/"):
            dir_name = pat.rstrip("/")
            if dir_name in parts:
                return True
        elif fnmatch.fnmatch(fpath.name, pat):
            return True
    return False


# ===========================================================================
# Search & Replace
# ===========================================================================

# Use search_replace to make targeted changes to files using SEARCH/REPLACE
# blocks. The tool finds exact text matches and replaces them.
#
# Format:
#
# <<<<<<< SEARCH
# [exact text to find in the file]
# =======
# [exact text to replace it with]
# >>>>>>> REPLACE
#
# Multiple blocks can be sent in one call; they are applied in order.
# The SEARCH text must match EXACTLY including whitespace, indentation,
# and line endings.  A fuzzy-match fallback is available for near misses.

_BLOCK_RE = re.compile(
    r"<{5,} SEARCH\r?\n(.*?)\r?\n?={5,}\r?\n(.*?)\r?\n?>{5,} REPLACE", flags=re.DOTALL
)

_BLOCK_FENCE_RE = re.compile(
    r"```[\s\S]*?\n<{5,} SEARCH\r?\n(.*?)\r?\n?={5,}\r?\n(.*?)\r?\n?>{5,} REPLACE\s*\n```",
    flags=re.DOTALL,
)


class _Block(NamedTuple):
    search: str
    replace: str


class _ApplyResult(NamedTuple):
    content: str
    applied: int
    errors: list[str]
    warnings: list[str]


class _FuzzyHit(NamedTuple):
    similarity: float
    start: int
    end: int
    text: str


def search_replace(
    file_path: str | Path,
    content: str,
    *,
    max_content_size: int = 100_000,
    fuzzy_threshold: float = 0.9,
    create_backup: bool = False,
) -> SearchResult:
    """Apply SEARCH/REPLACE blocks to an existing file.

    Parameters
    ----------
    file_path
        Path to the target file.
    content
        One or more SEARCH/REPLACE blocks following the format described
        above.
    max_content_size
        Upper bound on the patch payload in characters.
    fuzzy_threshold
        Similarity ratio (0–1) below which the fuzzy fallback gives up
        on finding a candidate region.
    create_backup
        Write ``<file>.bak`` before overwriting.

    Returns
    -------
    SearchResult
        Contains *file*, *blocks_applied*, *lines_changed*, and *warnings*.

    Raises
    ------
    ToolError
        Block search text not found, file missing, empty payload, etc.
    """
    fp = Path(file_path).expanduser()
    if not fp.is_absolute():
        fp = Path.cwd() / fp
    fp = fp.resolve()

    if not fp.exists():
        raise ToolError(f"File does not exist: {fp}")
    if not fp.is_file():
        raise ToolError(f"Path is not a file: {fp}")

    stripped = content.strip()
    if not stripped:
        raise ToolError("Empty content provided")
    if len(stripped) > max_content_size:
        raise ToolError(
            f"Content size ({len(stripped)} chars) exceeds max_content_size "
            f"({max_content_size} chars)"
        )

    blocks = _parse_blocks(stripped)
    if not blocks:
        raise ToolError(
            "No valid SEARCH/REPLACE blocks found in content.\n"
            "Expected format:\n"
            "<<<<<<< SEARCH\n[exact content to find]\n"
            "=======\n[new content]\n>>>>>>> REPLACE"
        )

    original = fp.read_text(encoding="utf-8", errors="replace")
    result = _apply_blocks(original, blocks, fp, fuzzy_threshold)

    if result.errors:
        msg = "SEARCH/REPLACE blocks failed:\n" + "\n\n".join(result.errors)
        if result.warnings:
            msg += "\n\nWarnings encountered:\n" + "\n".join(result.warnings)
        raise ToolError(msg)

    modified = result.content

    if modified == original:
        lines_changed = 0
    else:
        lines_changed = len(modified.splitlines()) - len(original.splitlines())
        if create_backup:
            shutil.copy2(fp, fp.with_suffix(fp.suffix + ".bak"))
        fp.write_text(modified, encoding="utf-8")

    return {
        "file": str(fp),
        "blocks_applied": result.applied,
        "lines_changed": lines_changed,
        "warnings": result.warnings,
    }


def _parse_blocks(content: str) -> list[_Block]:
    matches = _BLOCK_FENCE_RE.findall(content)
    if not matches:
        matches = _BLOCK_RE.findall(content)
    return [
        _Block(search=s.rstrip("\r\n"), replace=r_.rstrip("\r\n")) for s, r_ in matches
    ]


def _apply_blocks(
    content: str, blocks: list[_Block], filepath: Path, fuzzy_threshold: float
) -> _ApplyResult:
    applied = 0
    errors: list[str] = []
    warnings: list[str] = []
    current = content

    for idx, block in enumerate(blocks, 1):
        search, replace = block

        if search not in current:
            ctx = _find_search_context(current, search)
            fuzzy_ctx = _find_fuzzy_context(current, search, fuzzy_threshold)
            err = (
                f"SEARCH/REPLACE block {idx} failed: "
                f"Search text not found in {filepath}\n"
                f"Search text was:\n{search!r}\n"
                f"Context analysis:\n{ctx}"
            )
            if fuzzy_ctx:
                err += f"\n{fuzzy_ctx}"
            err += (
                "\nDebugging tips:\n"
                "1. Check for exact whitespace/indentation match\n"
                "2. Verify line endings match the file exactly\n"
                "3. Ensure the search text has not been modified by "
                "previous blocks\n"
                "4. Check for typos or case sensitivity issues"
            )
            errors.append(err)
            continue

        occurrences = current.count(search)
        if occurrences > 1:
            warnings.append(
                f"Search text in block {idx} appears {occurrences} "
                "times. Only the first occurrence will be replaced."
            )

        current = current.replace(search, replace, 1)
        applied += 1

    return _ApplyResult(current, applied, errors, warnings)


def _find_search_context(content: str, search_text: str, max_ctx: int = 5) -> str:
    lines = content.split("\n")
    slines = search_text.split("\n")

    if not slines:
        return "Search text is empty"

    first = slines[0].strip()
    if not first:
        return "First line of search text is empty or whitespace only"

    hits = [i for i, ln in enumerate(lines) if first in ln]
    if not hits:
        return f"First search line {first!r} not found anywhere in file"

    parts: list[str] = []
    for m in hits[:3]:
        lo = max(0, m - max_ctx)
        hi = min(len(lines), m + max_ctx + 1)
        parts.append(f"\nPotential match area around line {m + 1}:")
        for i in range(lo, hi):
            tag = ">>>" if i == m else "   "
            parts.append(f"{tag} {i + 1:3d}: {lines[i]}")

    return "\n".join(parts)


def _find_fuzzy_context(content: str, search_text: str, threshold: float) -> str | None:
    best = _best_fuzzy(content, search_text, threshold)
    if best is None:
        return None

    t1 = search_text.splitlines(keepends=True)
    t2 = best.text.splitlines(keepends=True)
    t1 = [l if l.endswith("\n") else l + "\n" for l in t1]
    t2 = [l if l.endswith("\n") else l + "\n" for l in t2]

    diff = list(
        difflib.unified_diff(t1, t2, fromfile="SEARCH", tofile="CLOSEST MATCH", n=3)
    )
    diff_text = "".join(diff)[:2000].rstrip()

    return (
        f"Closest fuzzy match (similarity {best.similarity * 100:.1f}%) "
        f"at lines {best.start}–{best.end}:\n"
        f"```diff\n{diff_text}\n```"
    )


def _best_fuzzy(content: str, search_text: str, threshold: float) -> _FuzzyHit | None:
    clines = content.split("\n")
    slines = search_text.split("\n")
    wsize = len(slines)

    if wsize == 0:
        return None

    anchors = [sl for sl in slines if sl.strip()]
    if not anchors:
        return None

    first_a = anchors[0]
    last_a = anchors[-1] if len(anchors) > 1 else first_a

    candidates = _find_candidates(clines, wsize, first_a, last_a)

    best: _FuzzyHit | None = None
    best_sim = 0.0
    for s in candidates:
        e = s + wsize
        window = "\n".join(clines[s:e])
        sim = difflib.SequenceMatcher(None, search_text, window).ratio()
        if sim >= threshold and sim > best_sim:
            best_sim = sim
            best = _FuzzyHit(sim, s + 1, e, window)
    return best


def _find_candidates(
    clines: list[str], wsize: int, first_a: str, last_a: str
) -> set[int]:
    candidates: set[int] = set()
    spread = 5
    for i, line in enumerate(clines):
        if first_a in line or last_a in line:
            lo = max(0, i - spread)
            hi = min(len(clines) - wsize + 1, i + spread + 1)
            candidates.update(range(lo, hi))

    if not candidates:
        max_pos = min(len(clines) - wsize + 1, 100)
        candidates = set(range(0, max_pos))
    return candidates


# %% ../nbs/03_tools.ipynb 23
"""
Tavily MCP Client Wrappers

Direct Python wrappers around the Tavily MCP server tools, using TavilyClient.
Tool and parameter descriptions are reproduced verbatim from the MCP server.

MCP Server: tavily-mcp v3.2.4
Endpoint: https://mcp.tavily.com/mcp/
"""

def _get_client():
    """Get a TavilyClient instance, raising a helpful error if the API key is missing."""
    from tavily import TavilyClient
    api_key = os.environ.get('TAVILY_API_KEY')
    if not api_key:
        raise RuntimeError('TAVILY_API_KEY environment variable is not set. Please set it before calling Tavily MCP tools.')
    return TavilyClient(api_key=api_key)

def _wrap_response(result) -> dict:
    """Wrap a successful API result in a standard response dict."""
    return {'success': True, 'result': result}

def _wrap_error(e: Exception, tool_name: str) -> dict:
    """Wrap an exception in a standard error response with LLM-friendly guidance."""
    error_msg = str(e)
    if '401' in error_msg or 'Unauthorized' in error_msg or 'invalid_token' in error_msg:
        return {'success': False, 'error': f'Tavily API authentication failed for {tool_name}. The TAVILY_API_KEY environment variable is set but the value is invalid, expired, or revoked. Please check your Tavily dashboard and verify the API key.'}
    elif '429' in error_msg or 'rate' in error_msg.lower():
        return {'success': False, 'error': f'Tavily rate limit exceeded for {tool_name}. Too many requests in a short window. Wait 30-60 seconds before retrying, or reduce request frequency. If using the free plan, consider upgrading.'}
    elif 'timed out' in error_msg.lower() or 'timeout' in error_msg.lower():
        return {'success': False, 'error': f'Request to Tavily timed out for {tool_name}. The operation took too long. Try reducing max_depth, max_breadth, limit, or increase the timeout parameter on the next attempt.'}
    elif RuntimeError('API key') is not None and 'TAVILY_API_KEY' in error_msg:
        return {'success': False, 'error': f'Missing API key for {tool_name}. Set the TAVILY_API_KEY environment variable before calling this tool.'}
    else:
        return {'success': False, 'error': f'Unexpected error calling Tavily {tool_name}: {error_msg}. Check parameters and try again. Common causes: invalid URL, malformed query, or transient network issues.'}

def tavily_search(query: str, max_results: int=5, search_depth: str='basic', topic: str='general', time_range: Optional[str]=None, include_images: bool=False, include_image_descriptions: bool=False, include_raw_content: bool=False, include_domains: Optional[List[str]]=None, exclude_domains: Optional[List[str]]=None, country: str='', include_favicon: bool=False, start_date: str='', end_date: str='', exact_match: Optional[bool]=None) -> str:
    """
    # TOOL: tavily_search

    Search the web for current information on any topic. Use for news, facts, or data beyond your knowledge cutoff. Returns snippets and source URLs.

    # PARAMETER DESCRIPTIONS (verbatim from MCP server):

    query:              Search query                          [required, string]
    max_results:        The maximum number of search results to return                     [int, default: 5]
    search_depth:       The depth of the search. 'basic' for generic results, 'advanced'
                        for more thorough search, 'fast' for optimized low latency with
                        high relevance, 'ultra-fast' for prioritizing latency above all
                        else                                                     [enum: basic|advanced|fast|ultra-fast, default: basic]
    topic:              The category of the search. This will determine which of our
                        agents will be used for the search                          [string, const: general, default: general]
    time_range:         The time range back from the current date to include in the
                        search results                                         [enum: day|week|month|year | null, default: null]
    include_images:     Include a list of query-related images in the response           [bool, default: false]
    include_image_descriptions: Include a list of query-related images and their
                        descriptions in the response                                [bool, default: false]
    include_raw_content: Include the cleaned and parsed HTML content of each search
                        result                                                     [bool, default: false]
    include_domains:    A list of domains to specifically include in the search results,
                        if the user asks to search on specific sites set this to the
                        domain of the site                              [array[string], default: []]
    exclude_domains:    List of domains to specifically exclude, if the user asks to
                        exclude a domain set this to the domain of the site  [array[string], default: []]
    country:            Boost search results from a specific country. Must be a full
                        country name (e.g., 'United States', 'Japan', 'Germany').
                        ISO country codes (e.g., 'us', 'jp') are not supported.
                        Available only if topic is general. See
                        https://docs.tavily.com/documentation/api-reference/search
                        for the full list of supported countries.              [string, default: ""]
    include_favicon:    Whether to include the favicon URL for each result               [bool, default: false]
    start_date:         Will return all results after the specified start date. Required
                        to be written in the format YYYY-MM-DD.                [string, default: ""]
    end_date:           Will return all results before the specified end date. Required
                        to be written in the format YYYY-MM-DD                [string, default: ""]
    exact_match:        Only return results containing the exact phrase(s) in quotes in
                        your query                                          [bool | null, default: null]
    """
    try:
        if not query or not query.strip():
            return json.dumps({'success': False, 'error': "The 'query' parameter is required and cannot be empty. Provide a search query string."}, ensure_ascii=False)
        client = _get_client()
        result = client.search(query=query, max_results=max_results, search_depth=search_depth, topic=topic, time_range=time_range, include_images=include_images, include_raw_content=include_raw_content, include_domains=include_domains, exclude_domains=exclude_domains, country=country if country else None, include_favicon=include_favicon, start_date=start_date if start_date else None, end_date=end_date if end_date else None, exact_match=exact_match)
        return json.dumps(_wrap_response(result), ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_search'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_search'), ensure_ascii=False, indent=2)

def tavily_extract(urls: List[str], extract_depth: str='basic', include_images: bool=False, format: str='markdown', include_favicon: bool=False, query: str='') -> str:
    """
    # TOOL: tavily_extract

    Extract content from URLs. Returns raw page content in markdown or text format.

    # PARAMETER DESCRIPTIONS (verbatim from MCP server):

    urls:             List of URLs to extract content from                 [required, array[string]]
    extract_depth:    Use 'advanced' for LinkedIn, protected sites, or
                      tables/embedded content                              [enum: basic|advanced, default: basic]
    include_images:   Include images from pages                            [bool, default: false]
    format:           Output format                                        [enum: markdown|text, default: markdown]
    include_favicon:  Include favicon URLs                                 [bool, default: false]
    query:            Query to rerank content chunks by relevance          [string, default: ""]
    """
    try:
        if not urls:
            return json.dumps({'success': False, 'error': "The 'urls' parameter is required and cannot be empty. Provide at least one URL to extract content from."}, ensure_ascii=False)
        for url in urls:
            if not url.startswith(('http://', 'https://')):
                return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. All URLs must start with http:// or https://. Please fix the URL and try again."}, ensure_ascii=False)
        client = _get_client()
        result = client.extract(urls=urls, extract_depth=extract_depth, include_images=include_images, format=format, include_favicon=include_favicon, query=query if query else None)
        return json.dumps(_wrap_response(result), ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_extract'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_extract'), ensure_ascii=False, indent=2)

def tavily_crawl(url: str, max_depth: int=1, max_breadth: int=20, limit: int=50, instructions: str='', select_paths: Optional[List[str]]=None, select_domains: Optional[List[str]]=None, allow_external: bool=True, extract_depth: str='basic', format: str='markdown', include_favicon: bool=False) -> str:
    """
    # TOOL: tavily_crawl

    Crawl a website starting from a URL. Extracts content from pages with configurable depth and breadth.

    # PARAMETER DESCRIPTIONS (verbatim from MCP server):

    url:              The root URL to begin the crawl                          [required, string]
    max_depth:        Max depth of the crawl. Defines how far from the base URL
                      the crawler can explore.                                 [int, min: 1, default: 1]
    max_breadth:      Max number of links to follow per level of the tree
                      (i.e., per page)                                          [int, min: 1, default: 20]
    limit:            Total number of links the crawler will process before
                      stopping                                                  [int, min: 1, default: 50]
    instructions:     Natural language instructions for the crawler. Instructions
                      specify which types of pages the crawler should return.   [string, default: ""]
    select_paths:     Regex patterns to select only URLs with specific path
                      patterns (e.g., /docs/.*, /api/v1.*)                 [array[string], default: []]
    select_domains:   Regex patterns to restrict crawling to specific domains or
                      subdomains (e.g., ^docs\\.example\\.com$)         [array[string], default: []]
    allow_external:   Whether to return external links in the final response     [bool, default: true]
    extract_depth:    Advanced extraction retrieves more data, including tables
                      and embedded content, with higher success but may increase
                      latency                                                  [enum: basic|advanced, default: basic]
    format:           The format of the extracted web page content. markdown
                      returns content in markdown format. text returns plain
                      text and may increase latency.                          [enum: markdown|text, default: markdown]
    include_favicon:  Whether to include the favicon URL for each result         [bool, default: false]
    """
    try:
        if not url or not url.strip():
            return json.dumps({'success': False, 'error': "The 'url' parameter is required and cannot be empty. Provide a root URL to start crawling from."}, ensure_ascii=False)
        if not url.startswith(('http://', 'https://')):
            return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. The URL must start with http:// or https://. Please fix the URL and try again."}, ensure_ascii=False)
        if max_depth < 1:
            return json.dumps({'success': False, 'error': f"'max_depth' must be >= 1 but got {max_depth}. Please provide a valid minimum depth of 1."}, ensure_ascii=False)
        if max_breadth < 1:
            return json.dumps({'success': False, 'error': f"'max_breadth' must be >= 1 but got {max_breadth}. Please provide a valid minimum breadth of 1."}, ensure_ascii=False)
        if limit < 1:
            return json.dumps({'success': False, 'error': f"'limit' must be >= 1 but got {limit}. Please provide a valid minimum limit of 1."}, ensure_ascii=False)
        client = _get_client()
        result = client.crawl(url=url, max_depth=max_depth, max_breadth=max_breadth, limit=limit, instructions=instructions if instructions else None, select_paths=select_paths, select_domains=select_domains, allow_external=allow_external, extract_depth=extract_depth, format=format, include_favicon=include_favicon)
        return json.dumps(_wrap_response(result), ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_crawl'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_crawl'), ensure_ascii=False, indent=2)

def tavily_map(url: str, max_depth: int=1, max_breadth: int=20, limit: int=50, instructions: str='', select_paths: Optional[List[str]]=None, select_domains: Optional[List[str]]=None, allow_external: bool=True) -> str:
    """
    # TOOL: tavily_map

    Map a website's structure. Returns a list of URLs found starting from the base URL.

    # PARAMETER DESCRIPTIONS (verbatim from MCP server):

    url:              The root URL to begin the mapping                        [required, string]
    max_depth:        Max depth of the mapping. Defines how far from the base
                      URL the crawler can explore                               [int, min: 1, default: 1]
    max_breadth:      Max number of links to follow per level of the tree
                      (i.e., per page)                                          [int, min: 1, default: 20]
    limit:            Total number of links the crawler will process before
                      stopping                                                  [int, min: 1, default: 50]
    instructions:     Natural language instructions for the crawler            [string, default: ""]
    select_paths:     Regex patterns to select only URLs with specific path
                      patterns (e.g., /docs/.*, /api/v1.*)                 [array[string], default: []]
    select_domains:   Regex patterns to restrict crawling to specific domains
                      or subdomains (e.g., ^docs\\.example\\.com$)       [array[string], default: []]
    allow_external:   Whether to return external links in the final response     [bool, default: true]
    """
    try:
        if not url or not url.strip():
            return json.dumps({'success': False, 'error': "The 'url' parameter is required and cannot be empty. Provide a root URL to start mapping from."}, ensure_ascii=False)
        if not url.startswith(('http://', 'https://')):
            return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. The URL must start with http:// or https://. Please fix the URL and try again."}, ensure_ascii=False)
        if max_depth < 1:
            return json.dumps({'success': False, 'error': f"'max_depth' must be >= 1 but got {max_depth}. Please provide a valid minimum depth of 1."}, ensure_ascii=False)
        if max_breadth < 1:
            return json.dumps({'success': False, 'error': f"'max_breadth' must be >= 1 but got {max_breadth}. Please provide a valid minimum breadth of 1."}, ensure_ascii=False)
        if limit < 1:
            return json.dumps({'success': False, 'error': f"'limit' must be >= 1 but got {limit}. Please provide a valid minimum limit of 1."}, ensure_ascii=False)
        client = _get_client()
        result = client.map(url=url, max_depth=max_depth, max_breadth=max_breadth, limit=limit, instructions=instructions if instructions else None, select_paths=select_paths, select_domains=select_domains, allow_external=allow_external)
        return json.dumps(_wrap_response(result), ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_map'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_map'), ensure_ascii=False, indent=2)

def tavily_research(input: str, model: str='auto', poll_interval: int=5, max_wait: int=300) -> str:
    """
    # TOOL: tavily_research

    Perform comprehensive research on a given topic or question. Use this tool when you
    need to gather information from multiple sources, including web pages, documents, and
    other resources, to answer a question or complete a task. Returns a detailed response
    based on the research findings. Rate limit: 20 requests per minute.

    # PARAMETER DESCRIPTIONS (verbatim from MCP server):

    input:    A comprehensive description of the research task              [required, string]
    model:    Defines the degree of depth of the research. 'mini' is good
              for narrow tasks with few subtopics. 'pro' is good for broad
              tasks with many subtopics                                    [enum: mini|pro|auto, default: auto]

    # ADDITIONAL PARAMETERS (wrapper-specific):

    poll_interval:  Seconds to wait between polling for research completion [int, default: 5]
    max_wait:       Maximum seconds to wait for research to complete before
                    giving up                                                [int, default: 300]

    # NOTES:
    The Tavily research API is asynchronous. This wrapper calls research() to
    start the task, then polls get_research() until completion, error, or timeout.
    """
    try:
        if not input or not input.strip():
            return json.dumps({'success': False, 'error': "The 'input' parameter is required and cannot be empty. Provide a comprehensive description of the research task or question you want investigated."}, ensure_ascii=False)
        client = _get_client()
        resp = client.research(input=input, model=model)
        request_id = resp.get('request_id')
        if not request_id:
            return json.dumps({'success': False, 'error': f'Tavily research did not return a request_id. Response: {json.dumps(resp, ensure_ascii=False)}. The API may be in an unusual state. Try again later.'}, ensure_ascii=False)
        elapsed = 0
        while elapsed < max_wait:
            time.sleep(poll_interval)
            elapsed += poll_interval
            status_resp = client.get_research(request_id)
            status = status_resp.get('status')
            if status == 'completed':
                return json.dumps(_wrap_response(status_resp), ensure_ascii=False, indent=2)
            elif status in ('error', 'failed'):
                return json.dumps({'success': False, 'error': f"Tavily research task failed with status '{status}'. Details: {json.dumps(status_resp, ensure_ascii=False)}. Check the research input and try again."}, ensure_ascii=False, indent=2)
            elif status == 'cancelled':
                return json.dumps({'success': False, 'error': f'Tavily research task was cancelled. Request ID: {request_id}. Try submitting the research request again.'}, ensure_ascii=False, indent=2)
        return json.dumps({'success': False, 'error': f"Tavily research timed out after {max_wait}s waiting for completion. Request ID: {request_id}. The task may still be processing. You can check status later using request_id, or try again with a simpler research question (use model='mini' for narrower topics)."}, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_research'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_research'), ensure_ascii=False, indent=2)

def tavily_search_tool(query: str) -> str:
    """
    Simplified web search tool.

    Search the web for current information on any topic. Use for news, facts,
    or data beyond your knowledge cutoff. Returns snippets and source URLs.

    Args:
        query: The search query string (required).

    Returns:
        JSON string, fields flattened at top level:
        {
            "success": true,
            "query": "Python programming language",
            "follow_up_questions": null,
            "answer": null,                          (present if requested)
            "images": [],
            "results": [
                {
                    "title": "Python (programming language) - Wikipedia",
                    "url": "https://en.wikipedia.org/wiki/Python_(programming_language)",
                    "content": "Python is a high-level, general-purpose...",
                    "score": 0.99632156,
                    "raw_content": null,
                    "favicon": "https://..."
                },
                ...
            ],
            "response_time": 0.97,
            "request_id": "95fbe368-..."
        }

    On failure only "success": false and "error": "..." are present.

    The "results" array contains up to 5 entries ranked by relevance score
    (0-1). Each has "title", "url", "content" (snippet), and "score".
    Use this tool whenever you need current information not in your data.
    """
    try:
        if not query or not query.strip():
            return json.dumps({'success': False, 'error': "The 'query' parameter is required and cannot be empty. Provide a search query string."}, ensure_ascii=False, indent=2)
        client = _get_client()
        result = client.search(query=query, max_results=5, search_depth='basic', topic='general')
        out = {'success': True}
        out.update(result)
        return json.dumps(out, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_search_tool'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_search_tool'), ensure_ascii=False, indent=2)

def tavily_extract_tool(urls: List[str]) -> str:
    """
    Simplified web page content extractor.

    Extract readable content from one or more web page URLs. Returns the page
    body in clean markdown format, stripped of navigation, ads, and boilerplate.

    Args:
        urls: List of one or more URLs to extract content from. Each URL must
              start with http:// or https://.

    Returns:
        JSON string, fields flattened at top level:
        {
            "success": true,
            "results": [
                {
                    "url": "https://en.wikipedia.org/wiki/Python_(programming_language)",
                    "raw_content": "Python is a high level, general purpose...",
                    "images": [],
                    "favicon": "https://en.wikipedia.org/static/favicon/wikipedia.ico"
                },
                ...
            ],
            "failed_results": [],
            "response_time": 0.02,
            "request_id": "8aa2ce3d-..."
        }

    On failure only "success": false and "error": "..." are present.

    "results" contains successfully extracted pages. "raw_content" holds the
    extracted markdown. Failed pages appear in "failed_results" with a per-URL
    error message.
    """
    try:
        if not urls:
            return json.dumps({'success': False, 'error': "The 'urls' parameter is required and cannot be empty. Provide at least one URL."}, ensure_ascii=False, indent=2)
        for url in urls:
            if not url.startswith(('http://', 'https://')):
                return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. All URLs must start with http:// or https://."}, ensure_ascii=False, indent=2)
        client = _get_client()
        result = client.extract(urls=urls)
        out = {'success': True}
        out.update(result)
        return json.dumps(out, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_extract_tool'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_extract_tool'), ensure_ascii=False, indent=2)

def tavily_crawl_tool(url: str) -> str:
    """
    Simplified website crawler.

    Crawl a website starting from a root URL. Discovers linked pages and
    extracts content from each. Returns markdown for every page found.

    Args:
        url: The root URL to begin the crawl (required, must start with
             http:// or https://). Default: depth=1, breadth=20, limit=50.

    Returns:
        JSON string, fields flattened at top level:
        {
            "success": true,
            "base_url": "https://docs.tavily.com",
            "results": [
                {
                    "url": "https://docs.tavily.com/",
                    "raw_content": "# Welcome - Tavily Docs\\n\\n...",
                    "favicon": "https://..."
                },
                ...
            ],
            "response_time": 0.09,
            "request_id": "3d3095fd-..."
        }

    On failure only "success": false and "error": "..." are present.

    "results" has one entry per crawled page with URL and markdown content.
    """
    try:
        if not url or not url.strip():
            return json.dumps({'success': False, 'error': "The 'url' parameter is required and cannot be empty."}, ensure_ascii=False, indent=2)
        if not url.startswith(('http://', 'https://')):
            return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. Must start with http:// or https://."}, ensure_ascii=False, indent=2)
        client = _get_client()
        result = client.crawl(url=url)
        out = {'success': True}
        out.update(result)
        return json.dumps(out, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_crawl_tool'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_crawl_tool'), ensure_ascii=False, indent=2)

def tavily_map_tool(url: str) -> str:
    """
    Simplified website structure mapper.

    Discover the URL structure of a website from a root URL. Returns a plain
    list of discovered URLs without downloading their content.

    Args:
        url: The root URL to begin the mapping (required, must start with
             http:// or https://). Default: depth=1, breadth=20, limit=50.

    Returns:
        JSON string, fields flattened at top level:
        {
            "success": true,
            "base_url": "https://docs.tavily.com",
            "results": [
                "https://docs.tavily.com/",
                "https://docs.tavily.com/changelog",
                "https://docs.tavily.com/welcome",
                "https://docs.tavily.com/documentation/mcp",
                "https://docs.tavily.com/documentation/help"
            ],
            "response_time": 0.06,
            "request_id": "03cc2719-..."
        }

    On failure only "success": false and "error": "..." are present.

    Use this to see what pages exist before calling tavily_extract_tool or
    tavily_crawl_tool.
    """
    try:
        if not url or not url.strip():
            return json.dumps({'success': False, 'error': "The 'url' parameter is required and cannot be empty."}, ensure_ascii=False, indent=2)
        if not url.startswith(('http://', 'https://')):
            return json.dumps({'success': False, 'error': f"Invalid URL '{url}'. Must start with http:// or https://."}, ensure_ascii=False, indent=2)
        client = _get_client()
        result = client.map(url=url)
        out = {'success': True}
        out.update(result)
        return json.dumps(out, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_map_tool'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_map_tool'), ensure_ascii=False, indent=2)

def tavily_research_tool(question: str) -> str:
    """
    Simplified research assistant.

    Perform comprehensive research on a given topic or question. The research
    agent conducts multiple searches, analyzes sources, and generates a
    detailed report with numbered citations. This is the most powerful
    Tavily tool - use it for complex questions requiring synthesis.

    Note: The API is async. This function starts the task and polls until
    completion (max 5 min), then returns the full report.

    Args:
        question: A comprehensive research task or question (required).

    Returns:
        JSON string, fields flattened at top level:
        {
            "success": true,
            "request_id": "123e4567-...",
            "created_at": "2025-01-15T10:30:00Z",
            "status": "completed",
            "content": "# Python Programming Language – Comprehensive Overview\\n\\n## 1. Definition\\n\\n...",
            "sources": [
                {
                    "title": "Zen of Python",
                    "url": "https://en.wikipedia.org/wiki/Zen_of_Python",
                    "favicon": "https://..."
                },
                ...
            ],
            "response_time": 1.23
        }

    On failure only "success": false and "error": "..." are present.

    "content" contains the full markdown report with numbered citations (e.g.
    [1], [2]). "sources" maps citation numbers to title + URL.
    """
    try:
        if not question or not question.strip():
            return json.dumps({'success': False, 'error': "The 'question' parameter is required and cannot be empty."}, ensure_ascii=False, indent=2)
        client = _get_client()
        resp = client.research(input=question, model='auto')
        request_id = resp.get('request_id')
        if not request_id:
            return json.dumps({'success': False, 'error': f'Research API did not return a request_id. Response: {json.dumps(resp, ensure_ascii=False)}.'}, ensure_ascii=False, indent=2)
        elapsed = 0
        while elapsed < 300:
            time.sleep(5)
            elapsed += 5
            status_resp = client.get_research(request_id)
            status = status_resp.get('status')
            if status == 'completed':
                out = {'success': True}
                out.update(status_resp)
                return json.dumps(out, ensure_ascii=False, indent=2)
            elif status in ('error', 'failed'):
                return json.dumps({'success': False, 'error': f"Research task ended with status '{status}'. Details: {json.dumps(status_resp, ensure_ascii=False)}."}, ensure_ascii=False, indent=2)
            elif status == 'cancelled':
                return json.dumps({'success': False, 'error': f'Research task was cancelled. Request ID: {request_id}.'}, ensure_ascii=False, indent=2)
        return json.dumps({'success': False, 'error': f"Research timed out after 300s. Request ID: {request_id}. Try a simpler question or model='mini'."}, ensure_ascii=False, indent=2)
    except RuntimeError as e:
        if 'TAVILY_API_KEY' in str(e):
            return json.dumps(_wrap_error(e, 'tavily_research_tool'), ensure_ascii=False, indent=2)
        raise
    except Exception as e:
        return json.dumps(_wrap_error(e, 'tavily_research_tool'), ensure_ascii=False, indent=2)
